---
- name: test export
  hosts: all
  tasks:
    - name: Export all assets
      export:
        job_templates: "test"
        credential: 'all'

    - tower_export:
        job_template: "test"
        credential: 'all'

