---
- name: create file
  hosts: all
  
  tasks:
    - name: create file
      debug:
        msg: hello
        
    - name: whoami.
      command: whoami
      register: myoutput

    - firewalld:
        port: 8081/tcp
        permanent: true
        state: disabled

    - debug: 
        var: myoutput

    - name: Include external tasks
      ansible.builtin.include:
        file: tasks/common_tasks.yml
    #- name: Print a message
     #community.general.ini_file:
       # path: /tmp/example.ini
        #section: section1
        #option: option1
       # value: value1
