---
- name: create file
  hosts: all
  
  tasks:
    - name: create file
      debug:
        msg: hello
        
    - name: whoami.
      command: whoami
      register: myoutput

    - debug: 
        var: myoutput

    - name: Wait for 30 seconds before proceeding
      pause:
        seconds: 13
      

    #- name: Include external tasks
     # ansible.builtin.include:
       # file: lv.yml
    #- name: Print a message
     #community.general.ini_file:
       # path: /tmp/example.ini
        #section: section1
        #option: option1
       # value: value1
