---
- name: create file
  hosts: all
  collections_paths: 
  
  tasks:
    - name: create file
      debug:
        msg: hello
        
    - name: whoami.
      command: whoami
      register: myoutput

    - firewalld:
        port: 8081/tcp
        permanent: true
        state: disabled

    - debug: 
        var: myoutput
        
    #- name: Print a message
     #community.general.ini_file:
       # path: /tmp/example.ini
        #section: section1
        #option: option1
       # value: value1
