---
- name: create file
  hosts: all
  tasks:
    - name: create file
      debug:
        msg: hello
        
    - name: whoami.
      ansible.builtin.command: whoami
      register: myoutput

    - ansible.builtin.debug: 
        var: myoutput
