---
- name: create file
  hosts: all
  
  tasks:
    - name: create file
      debug:
        msg: hello
        
    - name: whoami.
      ansible.builtin.command: whoami
      register: myoutput

    - ansible.posix.firewalld:
        port: 8081/tcp
        permanent: true
        state: disabled

    - ansible.builtin.debug: 
        var: myoutput
