---
- name: create file
  hosts: all
  
  tasks:
    - name: create file
      debug:
        msg: hello
        
    - name: whoami.
      command: whoami
      register: myoutput

    - firewalld:
        port: 8081/tcp
        permanent: true
        state: disabled

    - debug: 
        var: myoutput
        
    - name: Print a message
      community.general.echo:
        msg: "Hello from the community.general.echo module!"
