---
- hosts: all
  vars:
    ansible_become: true
    ansible_become_user: root
    ansible_become_password: redhat
  tasks: 
    - name: Install package
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - "telnet"
        - "nmap"
      register: install_status

    - debug:
        msg: install_status
