---
- name: Do not permit traffic in the default zone on port 8081/tcp
  hosts: all
  tasks:
    - name: Disable port 8081/tcp in firewalld
      ansible.posix.firewalld:
        port: 8081/tcp  # Corrected port number
        permanent: true
        state: disabled
