---
- name: Stonebranch Logical Volume
  hosts: all
  become: true
  tasks:
    - community.general.lvg:
        vg: datavg
        state: present
        
    - community.general.lvol:
        lv: stonebranchlv
        vg: datavg
        size: 1g
        state: present
