---
- name: Print a path example
  hosts: all
  vars_files:
    - /runner/projects/DRILL/test_details.yml
  tasks:
    - name: Edit Startup Properties File
      debug: 
        msg: hello 
      with_items:
        - \runner\projects\DRILL\nodemanager\test_startup.properties
