---
- name: Checking if hosts are reachable
  hosts: all
  gather_facts: true
  tasks:
    - name: ensure if host is online
      ansible.builtin.ping:
      register: ping_result
      
    - name: show result of ping
      ansible.builtin.debug:
        var: "{{ ping_result }}"
