---
- name: Debug output from vars section
  hosts: all
  gather_facts: no
  tasks:
    - name: Debug my_variable
      ansible.builtin.debug:
        msg: "{{ my_variable }}"

    - name: Debug another_variable
      ansible.builtin.debug:
        msg: "{{ another_variable }}"

