---
- name: Get a list of the hosts
  hosts: all
  gather_facts: false
  tasks:
  - name: Get a list of the hosts
    vmware.vmware_rest.vcenter_host_info:
    register: my_hosts

  - name: Print the list of hosts
    debug:
      var: my_hosts
