---
- name: Install firefox
  hosts: all
  tasks:
    - name: Install Firefox
      chocolatey.chocolatey.win_chocolatey:
        name: '{{ item }}'
        state: present
      loop:
        - firefox
