---
- name: hello_never_runs_wait_16m_fail
  hosts: all
  sources:
    - name: trigger_once
      eda.builtin.range:
        limit: 1
  rules:
    - name: Wait 16 minutes then fail before Hello job template
      condition: event.i == 0
      action:
        run_job_template:
          name: fifteen_min
          organization: Default
          retries: 0
